### ISSUE TITLE
Task #4

### ISSUE THREAD

**Issue by oLESHIYka** [ozoncp/ocp-snippet-api#4]
- Добавить интерфейсы Repo и Flusher
- Сгенерировать моки для Repo с помощью mockgen
- Реализовать имплементацию flusher для интерфейса Flusher
- Написать тестовые сценарии с помощью ginkgo и gomega

**Comment by rusdevops** [comment]
Оформи пожалуйста в виде **Pull Request**-а и назначь @LiFeAiR в качестве ревьювера.

**Comment by oLESHIYka** [comment]
@rusdevops Про PR я не забыл) Просто хотел ещё с линтером на локальной машине поиграться, потом уже на проверку направлять. Но спасибо за уточнение ревьювера)
